swagger: '2.0'
info:
  title: HR API
  description: |
    API to retrieve the departments, position titles, and ID's tied to a department and business center.
  version: '1.0'
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/hr-api
schemes:
  - https
produces:
  - application/json
basePath: /v1/hr
paths:
  /positions:
    get:
      summary: List positions
      description: List position (job) titles and numbers in a single business center and department.
      parameters:
        - in: query
          name: type
          description: The type of positions to list. Currently the API only supports "student" positions.
          required: true
          type: string
        - $ref: '#/parameters/businessCenter'
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: List of positions
          schema:
            $ref: "#/definitions/PositionsResultObject"
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
  /departments:
    get:
      summary: List departments
      description: Return org code and org description (departments) for a single business center
      parameters:
        - $ref: '#/parameters/businessCenter'
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: List of departments
          schema:
            $ref: "#/definitions/DepartmentsResultObject"
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

parameters:
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed
  businessCenter:
    name: businessCenter
    in: query
    description: "4-character business center name"
    required: true
    type: string

definitions:
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
  PositionsResultObject:
    properties:
      data:
        type: array
        items:
          properties:
            id:
              type: string
              example: "C12345"
            type:
              type: string
              example: position
            attributes:
              properties:
                title:
                  type: string
                  description: Position title.
                businessCenter:
                  type: string
                  description: Name of the business center
                positionNumber:
                  type: string
                  description: Position number
                  example: "C12345"
                organizationCode:
                  type: string
                  description: Numeric orgCode for the department
                lowSalaryPoint:
                  type: number
                  format: float
                  description: Low point for position salary
                  example: 10.5
                highSalaryPoint:
                  type: number
                  format: float
                  description: High point for position salary
                  example: 15.25
  DepartmentsResultObject:
    properties:
      data:
        type: array
        items:
          properties:
            id:
              type: string
              example: "123456"
            type:
              type: string
              example: department
            attributes:
              properties:
                name:
                  type: string
                  description: Name of the department usually referred to as orgDescription.
                businessCenter:
                  type: string
                  description: Name of the business center
                organizationCode:
                  type: string
                  example: "123456"
                  description: Numeric orgCode for the department